"""
AlphaForge — Strategy Tear Sheet
=================================
Generates a professional HTML strategy tear sheet similar to institutional
quant research summaries.

Outputs
-------
- HTML (self-contained, embeddable)
- CSV metrics summary

Disclaimer
----------
All output is for research and educational purposes only.
This is not investment advice. Past performance does not guarantee
future results.
"""

from __future__ import annotations

import base64
import logging
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.io import to_html

# ── Logo helper ───────────────────────────────────────────────────────────────

_ASSETS       = Path(__file__).resolve().parent.parent.parent / "assets"
_LOGO_PATH      = _ASSETS / "logo.png"       # full ALPHAFORGE wordmark
_LOGO_MARK_PATH = _ASSETS / "logo_mark.png"  # clean AF blade emblem


def _logo_b64_img(height: int = 44) -> str:
    """
    Embed logo as base64 <img> in the HTML tear sheet.
    Uses assets/logo.png or assets/logo_mark.png when present; falls back to ⚡.
    """
    for p in (_LOGO_PATH, _LOGO_MARK_PATH):
        if p.exists():
            b64 = base64.b64encode(p.read_bytes()).decode()
            return (
                f'<img src="data:image/png;base64,{b64}" height="{height}" '
                f'style="vertical-align:middle; border-radius:4px;" alt="AlphaForge">'
            )
    return '<span style="font-size:1.6rem; margin-right:8px;">⚡</span>'

logger = logging.getLogger(__name__)

_DISCLAIMER = (
    "This tear sheet is generated by AlphaForge for research and educational "
    "purposes only. Past performance does not guarantee future results. "
    "This is not investment advice. All metrics are historical and "
    "subject to estimation error."
)

# ── Formatting helpers ────────────────────────────────────────────────────────

def _pct(v, dec: int = 2) -> str:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "N/A"
    return f"{v * 100:+.{dec}f}%"

def _num(v, dec: int = 3) -> str:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "N/A"
    return f"{v:.{dec}f}"

def _usd(v) -> str:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "N/A"
    return f"${v:,.0f}"


# ── Embedded chart HTML ───────────────────────────────────────────────────────

def _equity_html(equity_df: pd.DataFrame, name: str) -> str:
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=equity_df.index, y=equity_df["Portfolio_Value"],
        mode="lines", name=name,
        line=dict(color="#00D4FF", width=2),
    ))
    fig.update_layout(
        template="plotly_dark", title="Portfolio Value",
        height=280, margin=dict(l=50, r=20, t=40, b=30),
        paper_bgcolor="#151B2E", plot_bgcolor="#151B2E",
        yaxis_title="Value ($)",
    )
    return to_html(fig, include_plotlyjs="cdn", full_html=False)


def _drawdown_html(equity_df: pd.DataFrame) -> str:
    pv   = equity_df["Portfolio_Value"]
    peak = pv.cummax()
    dd   = (pv - peak) / peak * 100

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=dd.index, y=dd,
        mode="lines", fill="tozeroy", name="Drawdown %",
        line=dict(color="#FF4444", width=1),
        fillcolor="rgba(255,68,68,0.15)",
    ))
    fig.update_layout(
        template="plotly_dark", title="Drawdown (%)",
        height=200, margin=dict(l=50, r=20, t=40, b=30),
        paper_bgcolor="#151B2E", plot_bgcolor="#151B2E",
        yaxis_title="Drawdown (%)",
    )
    return to_html(fig, include_plotlyjs=False, full_html=False)


def _rolling_sharpe_html(returns: pd.Series, name: str, window: int = 63) -> str:
    rs = returns.rolling(window).mean() / returns.rolling(window).std() * np.sqrt(252)
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=rs.index, y=rs, mode="lines", name=f"Rolling Sharpe ({window}d)",
        line=dict(color="#FFD700", width=1.5),
    ))
    fig.add_hline(y=0, line_dash="dash", line_color="#888", line_width=1)
    fig.update_layout(
        template="plotly_dark", title=f"Rolling {window}-Day Sharpe",
        height=200, margin=dict(l=50, r=20, t=40, b=30),
        paper_bgcolor="#151B2E", plot_bgcolor="#151B2E",
    )
    return to_html(fig, include_plotlyjs=False, full_html=False)


# ── Main generator ────────────────────────────────────────────────────────────

def generate_html_tear_sheet(
    metrics: dict,
    equity_df: pd.DataFrame,
    config: dict,
    strategy_name: str | None = None,
) -> str:
    """
    Generate a self-contained HTML tear sheet.

    Parameters
    ----------
    metrics : dict
        Merged output of compute_all_metrics + compute_risk_metrics +
        (optionally) compute_benchmark_metrics.
    equity_df : pd.DataFrame
        Equity curve with columns Portfolio_Value and Daily_Return.
    config : dict
        Sidebar config dict (for header metadata).
    strategy_name : str | None
        Overrides config["strategy"] in the header.

    Returns
    -------
    str
        Full HTML document.
    """
    name   = strategy_name or config.get("strategy", "Strategy")
    ticker = config.get("ticker", "—")
    bench  = config.get("benchmark", "—")
    start  = config.get("start_date", "—")
    end    = config.get("end_date", "—")
    ts     = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    logo_tag = _logo_b64_img(height=44)

    final_val = (
        equity_df["Portfolio_Value"].iloc[-1]
        if not equity_df.empty else None
    )

    # Build chart HTML
    eq_html = _equity_html(equity_df, name)       if not equity_df.empty else ""
    dd_html = _drawdown_html(equity_df)            if not equity_df.empty else ""
    rs_html = ""
    if not equity_df.empty and "Daily_Return" in equity_df.columns:
        rs_html = _rolling_sharpe_html(
            equity_df["Daily_Return"].dropna(), name
        )

    # KPI table rows
    kpis = [
        ("Strategy",                  name),
        ("Asset",                     ticker),
        ("Benchmark",                 bench),
        ("Period",                    f"{start} → {end}"),
        ("Initial Capital",           _usd(config.get("initial_capital"))),
        ("Final Value",               _usd(final_val)),
        ("— Performance —",           ""),
        ("Cumulative Return",         _pct(metrics.get("Cumulative_Return"))),
        ("CAGR",                      _pct(metrics.get("CAGR"))),
        ("Annualised Volatility",     _pct(metrics.get("Volatility_Ann"))),
        ("— Risk-Adjusted —",        ""),
        ("Sharpe Ratio",              _num(metrics.get("Sharpe_Ratio"))),
        ("Sortino Ratio",             _num(metrics.get("Sortino_Ratio"))),
        ("Calmar Ratio",              _num(metrics.get("Calmar_Ratio"))),
        ("Omega Ratio",               _num(metrics.get("Omega_Ratio"))),
        ("Serenity Ratio",            _num(metrics.get("Serenity_Ratio"))),
        ("— Drawdown —",             ""),
        ("Max Drawdown",              _pct(metrics.get("Max_Drawdown"))),
        ("Ulcer Index",               _num(metrics.get("Ulcer_Index"), 4)),
        ("— Risk —",                  ""),
        ("VaR 95% (1-day hist.)",     _pct(metrics.get("VaR_95_Historical"))),
        ("Expected Shortfall 95%",    _pct(metrics.get("ES_95_Historical"))),
        ("— Benchmark Relative —",   ""),
        ("Beta",                      _num(metrics.get("Beta"))),
        ("Alpha (Annualised)",        _pct(metrics.get("Alpha_Ann"))),
        ("Tracking Error",            _pct(metrics.get("Tracking_Error"))),
        ("Information Ratio",         _num(metrics.get("Information_Ratio"))),
        ("— Trade Statistics —",     ""),
        ("Win Rate",                  _pct(metrics.get("Win_Rate"))),
        ("Profit Factor",             _num(metrics.get("Profit_Factor"))),
        ("Tail Ratio",                _num(metrics.get("Tail_Ratio"))),
    ]

    kpi_html = ""
    for label, value in kpis:
        if value == "":  # section header
            kpi_html += (
                f"<tr class='section'><td colspan='2'>{label}</td></tr>"
            )
        else:
            kpi_html += f"<tr><td>{label}</td><td class='val'>{value}</td></tr>"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AlphaForge Tear Sheet — {name}</title>
<script src="https://cdn.plot.ly/plotly-2.26.0.min.js"></script>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: #0E1117; color: #E0E0E0; padding: 1.5rem 2rem;
    font-size: 14px; line-height: 1.5;
  }}
  .header {{
    border-bottom: 2px solid #00D4FF;
    padding-bottom: 0.8rem; margin-bottom: 1.5rem;
    display: flex; justify-content: space-between; align-items: flex-end;
  }}
  .header h1 {{
    font-size: 1.6rem; font-weight: 900; letter-spacing: -0.03em;
    background: linear-gradient(135deg, #00D4FF 0%, #0099CC 100%);
    -webkit-background-clip: text; -webkit-text-fill-color: transparent;
    background-clip: text; display: inline-block; vertical-align: middle;
  }}
  .header-brand {{
    display: flex; align-items: center;
  }}
  .header .meta {{ color: #666; font-size: 0.78rem; text-align: right; }}
  .grid {{ display: grid; grid-template-columns: 340px 1fr; gap: 1.2rem; }}
  .card {{
    background: #151B2E; border: 1px solid #1E2A3A;
    border-radius: 10px; padding: 1rem;
  }}
  .card h3 {{
    color: #00D4FF; font-size: 0.75rem; text-transform: uppercase;
    letter-spacing: 0.12em; margin-bottom: 0.7rem;
    border-bottom: 1px solid #1E2A3A; padding-bottom: 0.4rem;
  }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.82rem; }}
  tr.section td {{
    background: #1A2238; color: #888; font-weight: 700;
    font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.1em;
    padding: 0.3rem 0.4rem; margin-top: 0.3rem;
  }}
  tr:not(.section) td {{ padding: 0.35rem 0.4rem; border-bottom: 1px solid #1A2238; }}
  td.val {{ text-align: right; font-weight: 700; color: #00D4FF; font-variant-numeric: tabular-nums; }}
  .charts {{ grid-column: 2; display: flex; flex-direction: column; gap: 0.8rem; }}
  .full-width {{ grid-column: 1 / -1; }}
  .disclaimer {{
    margin-top: 1.5rem; padding: 0.8rem 1rem;
    background: #1A1520; border-left: 3px solid #FF6B35;
    border-radius: 4px; font-size: 0.72rem; color: #888;
  }}
  .footer {{
    text-align: center; margin-top: 1rem; color: #444; font-size: 0.7rem;
  }}
</style>
</head>
<body>

<div class="header">
  <div>
    <div class="header-brand">
      {logo_tag}
      <h1>AlphaForge — Strategy Tear Sheet</h1>
    </div>
    <div style="color:#888; font-size:0.8rem; margin-top:0.3rem;">
      {name} &nbsp;·&nbsp; {ticker} &nbsp;·&nbsp; {start} to {end}
    </div>
  </div>
  <div class="meta">Generated: {ts}<br>AlphaForge Research Platform</div>
</div>

<div class="grid">
  <div class="card">
    <h3>📊 Performance &amp; Risk Metrics</h3>
    <table>{kpi_html}</table>
  </div>

  <div class="charts">
    <div class="card">{eq_html}</div>
    <div class="card">{dd_html}</div>
    <div class="card">{rs_html}</div>
  </div>
</div>

<div class="disclaimer">⚠️ {_DISCLAIMER}</div>
<div class="footer">
  {_logo_b64_img(height=16)} &nbsp;AlphaForge Quantitative Research Platform &nbsp;·&nbsp;
  github.com/shahwfabian/AlphaForge
</div>

</body>
</html>"""

    return html


# ── CSV export ────────────────────────────────────────────────────────────────

def generate_csv_report(metrics: dict, config: dict) -> str:
    """
    Generate a flat CSV string of all metrics and config values.

    Returns
    -------
    str
        CSV text suitable for st.download_button.
    """
    PCT_KEYS = {
        "Cumulative_Return", "CAGR", "Volatility_Ann", "Max_Drawdown",
        "Win_Rate", "VaR_95_Historical", "VaR_99_Historical",
        "ES_95_Historical", "ES_99_Historical", "Alpha_Ann",
        "Tracking_Error",
    }

    lines = ["Metric,Value"]

    # Config header
    for k in ("strategy", "ticker", "benchmark", "start_date", "end_date",
              "initial_capital", "transaction_cost", "slippage"):
        lines.append(f"{k},{config.get(k, '')}")

    lines.append("---,---")

    # Metrics
    for k, v in metrics.items():
        if isinstance(v, float) and np.isnan(v):
            val = "N/A"
        elif isinstance(v, float):
            val = f"{v*100:.4f}%" if k in PCT_KEYS else f"{v:.6f}"
        else:
            val = str(v)
        lines.append(f"{k},{val}")

    return "\n".join(lines)
